export const path = {
  homePage: "/",
  category: "/category/:categoryName",
  pageNotFound: "*",
  signUp: "/sign-up",
  logIn: "/log-in",
  student: "/student",
  dashboard: "dashboard",
  // signIn: "/dang-nhap",
  // listJob: "/list-job",
  // admin: "/admin",
  // managerUser: "manager-user",
  // createUser: "create-user",
  // register: "/dang-ki",
  // adminLogIn: "/admin-login",
  // inFoUser: "thong-tin-tai-khoan",
  // student: "/student",
  // myLesson: "bai-hoc-cua-toi",
  myCourse: "my-courses",
  blog: "blog",
  contact: "contact",
  myAccount: "my-account",
  myLearning: "my-learning",
  coursesDetail: "courses-detail/:id",
};
