export const path = {
  homePage: "/",
  category: "/category/:maDanhMuc",
  pageNotFound: "*",
  signUp: "/sign-up",
  logIn: "/log-in",
  student: "/student",
  teacher: "/teacher",
  admin: "/admin",
  dashboard: "dashboard",
  managerUser: "manager-user",
  managerCategory: "manager-category",
  myCourse: "my-courses",
  blog: "blog",
  contact: "contact",
  myAccount: "my-account",
  myLearning: "my-learning",
  coursesDetail: "courses-detail/:id",
  managerCourse: "manager-course",
  cart: "cart",
};
