export const path = {
  homePage: "/",
  category: "/category/:maDanhMuc",
  pageNotFound: "*",
  signUp: "/sign-up",
  logIn: "/log-in",
  student: "/student",
  teacher: "/teacher",
  admin: "/admin",
  dashboard: "dashboard",
  // signIn: "/dang-nhap",
  // listJob: "/list-job",
  // admin: "/admin",
  managerUser: "manager-user",
  managerCategory: "manager-category",
  // createUser: "create-user",
  // register: "/dang-ki",
  // adminLogIn: "/admin-login",
  // inFoUser: "thong-tin-tai-khoan",
  // student: "/student",
  // myLesson: "bai-hoc-cua-toi",
  myCourse: "my-courses",
  blog: "blog",
  contact: "contact",
  myAccount: "my-account",
  myLearning: "my-learning",
  coursesDetail: "courses-detail/:id",
  managerCourse: "manager-course",
  cart: "cart",
};
